server:
 port: 8082
 
spring:
 application:
  name: API-Gateway
  
eureka:
 client:
  registry-with-eureka: true
  fetch-registry: true
  service-url:
   default-zone: http://localhost:8761/eureka/
 instance:
  hostname: localhost